# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0002_usernews'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernews',
            name='image_page',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
