# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 08:07
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
from django.contrib.auth.models import User
from telegrambot.models import UserProfile, UserSettings


def default_settings(apps, schema_editor):
    users = User.objects.all()
    for user in users:
        us = UserSettings.objects.create()
        ue = UserProfile.objects.filter(user=user)
        if ue:
            ue[0].user_settings = us
            ue[0].save()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegrambot', '0003_usernews_image_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNewsList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_publish', models.DateTimeField(default=datetime.datetime(2001, 8, 15, 8, 15, 12, tzinfo=utc))),
                ('number_of_news', models.PositiveIntegerField(verbose_name='Number of News of list')),
                ('message_id', models.PositiveIntegerField(null=True, verbose_name='Message ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('live_news', models.BooleanField(default=False)),
                ('interval_news_list', models.PositiveSmallIntegerField(default=60)),
                ('last_news_list', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.UserNewsList', verbose_name='Last News List')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user_settings',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='telegrambot.UserSettings', verbose_name='User Settings'),
        ),
        migrations.RunPython(default_settings)
    ]
