# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-16 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0005_messagefromuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='interval_news_list',
            field=models.PositiveSmallIntegerField(default=180),
        ),
    ]
