# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-24 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegrambot', '0007_auto_20160919_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='stopped',
            field=models.BooleanField(default=False, verbose_name='Bot Stopped'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Bot Blocked'),
        ),
    ]
