# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegrambot', '0009_auto_20160929_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='interval_news_list',
            field=models.PositiveSmallIntegerField(default=1440),
        ),
    ]
