# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0012_categorycode_activation'),
        ('telegrambot', '0010_auto_20161005_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, null=True, to='rss.CategoryCode',
                                         verbose_name='Interest user categories'),
        ),
    ]
