# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-09 09:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss', '0012_categorycode_activation'),
        ('telegrambot', '0011_userprofile_interest_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLiveNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.News')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='interest_categories',
            field=models.ManyToManyField(blank=True, to='rss.CategoryCode', verbose_name='Interest user categories'),
        ),
    ]
