# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 08:05
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telegrambot', '0012_auto_20161009_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSearchList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('datetime_start', models.DateTimeField(default=datetime.datetime(2001, 8, 15, 8, 15, 12, tzinfo=utc))),
                ('datetime_publish',
                 models.DateTimeField(default=datetime.datetime(2001, 8, 15, 8, 15, 12, tzinfo=utc))),
                ('number_of_news', models.PositiveIntegerField(verbose_name='Number of News of list')),
                ('message_id', models.PositiveIntegerField(null=True, verbose_name='Message ID')),
                ('page', models.PositiveIntegerField(default=1, verbose_name='Page that list is')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL,
                                           verbose_name='User')),
            ],
        ),
    ]
