# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegrambot', '0013_usersearchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersettings',
            name='interval_news_list',
            field=models.PositiveSmallIntegerField(default=120),
        ),
    ]
