# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-21 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegrambot', '0015_usersearchlist_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChannelPublish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_username', models.CharField(max_length=120)),
                ('last_news', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
