# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-22 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegrambot', '0016_channelpublish'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='private',
            field=models.BooleanField(default=False, verbose_name='Private'),
        ),
    ]
