# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-12-06 12:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('telegrambot', '0018_auto_20161130_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Activation'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='interval_news_list',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
