# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 13:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Like'), (False, 'Unlike')], default=True)),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='like_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Likes'),
        ),
        migrations.AddField(
            model_name='newslike',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.News'),
        ),
        migrations.AddField(
            model_name='newslike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
