# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-10 10:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20160830_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='rssfeeds',
            name='time_delay',
            field=models.BooleanField(default=False, verbose_name='Time Delay'),
        ),
    ]
