# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-28 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0002_auto_20160824_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeeds',
            name='order',
            field=models.CharField(blank=True, choices=[('D', 'Date'), ('V', 'Visit'), ('F', 'Front')], max_length=50, verbose_name='RSS Order'),
        ),
    ]
