# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 06:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0003_rssfeeds_time_delay'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsAgency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=50, verbose_name='Web site')),
                ('name', models.CharField(max_length=50, verbose_name='site Name')),
                ('fa_name', models.CharField(max_length=50, verbose_name='Persian Name')),
                ('selector', models.CharField(blank=True, max_length=100)),
                ('summary_selector', models.CharField(blank=True, max_length=100)),
                ('image_selector', models.CharField(blank=True, max_length=100)),
                ('time_delay', models.BooleanField(default=False, verbose_name='Time Delay')),
            ],
        ),
        migrations.AddField(
            model_name='rssfeeds',
            name='news_agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rss.NewsAgency'),
        ),
    ]
