# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-13 06:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0004_auto_20160913_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rssfeeds',
            name='fa_name',
        ),
        migrations.RemoveField(
            model_name='rssfeeds',
            name='image_selector',
        ),
        migrations.RemoveField(
            model_name='rssfeeds',
            name='name',
        ),
        migrations.RemoveField(
            model_name='rssfeeds',
            name='selector',
        ),
        migrations.RemoveField(
            model_name='rssfeeds',
            name='summary_selector',
        ),
        migrations.RemoveField(
            model_name='rssfeeds',
            name='time_delay',
        ),
        migrations.RemoveField(
            model_name='rssfeeds',
            name='url',
        ),
        migrations.AlterField(
            model_name='rssfeeds',
            name='news_agency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rss.NewsAgency'),
            preserve_default=False,
        ),
    ]
