# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-14 06:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0006_auto_20160914_1029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basenews',
            old_name='all',
            new_name='all_rss',
        ),
    ]
