# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-28 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0008_basenews_news_agency'),
    ]

    operations = [
        migrations.AddField(
            model_name='basenews',
            name='source_type',
            field=models.IntegerField(choices=[(1, 'Website RSS'), (2, 'Codal')], default=1,
                                      verbose_name='Type of source'),
        ),
        migrations.AlterField(
            model_name='rssfeeds',
            name='order',
            field=models.CharField(blank=True, choices=[('D', 'Date'), ('V', 'Visit'), ('F', 'Front'),
                                                        ('VF', 'Visit in frontpage')], max_length=50,
                                   verbose_name='RSS Order'),
        ),
    ]
