# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0010_auto_20161007_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeeds',
            name='category_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='rss.CategoryCode'),
        ),
    ]
