# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0011_auto_20161007_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorycode',
            name='activation',
            field=models.BooleanField(default=True, verbose_name='Activation'),
        ),
    ]
