# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0015_auto_20161110_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='telegram/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='news',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='telegram/%Y/%m/%d/'),
        ),
    ]
