# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-17 08:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0016_auto_20161114_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bad_news',
            fields=[
                ('news_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='rss.News')),
            ],
            bases=('rss.news',),
        ),
        migrations.CreateModel(
            name='TelegramPost',
            fields=[
                ('id', models.CharField(max_length=63, primary_key=True, serialize=False, verbose_name='Message ID')),
                ('channel_id', models.CharField(max_length=63, verbose_name='Peer ID')),
            ],
        ),
    ]
