# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-19 11:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0017_telegrampost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadNews',
            fields=[
                ('news_ptr',
                 models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True,
                                      primary_key=True, serialize=False, to='rss.News')),
            ],
            bases=('rss.news',),
        ),
    ]
