# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-17 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0017_bad_news_telegrampost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bad_news',
            new_name='BadNews',
        ),
    ]
