# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-26 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0018_badnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pdf_link',
            field=models.URLField(blank=True, max_length=600, null=True, verbose_name='pdf link'),
        ),
    ]
