# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-30 10:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0019_news_pdf_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='unlike_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Un-Likes'),
        ),
    ]
