# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-30 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0020_news_unlike_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newslike',
            name='status',
        ),
        migrations.AddField(
            model_name='newslike',
            name='vote',
            field=models.CharField(choices=[('L', 'Like'), ('U', 'Unlike'), ('D', 'Discard')], default='D',
                                   max_length=1),
        ),
    ]
