# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-30 12:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('rss', '0021_auto_20161130_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegrampost',
            name='news',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                       to='rss.News', verbose_name='News'),
        ),
        migrations.AddField(
            model_name='telegrampost',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='rss.TelegramPost', verbose_name='Replied to'),
        ),
    ]
