# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-24 05:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('wiki_name', models.CharField(max_length=70, null=True)),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('A', 'Activated'), ('R', 'Rejected'), ('D', 'Deleted')], default='N', max_length=1)),
                ('followers', models.IntegerField(default=0)),
                ('news_count', models.IntegerField(default=0)),
                ('last_news', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(choices=[(True, 'Fallow'), (False, 'Unfallow')], default=True)),
                ('score', models.SmallIntegerField(default=0)),
                ('last_news', models.DateTimeField(blank=True, null=True)),
                ('news_count', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
