# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 07:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('N', 'New'), ('P', 'Pending'), ('A', 'Activated'), ('R', 'Rejected'), ('D', 'Deleted')], default='N', max_length=1)),
                ('followers', models.IntegerField(default=0)),
                ('news_count', models.IntegerField(default=0)),
                ('last_news', models.DateTimeField()),
            ],
        ),
    ]
