# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 08:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.SmallIntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rss.News')),
            ],
        ),
        migrations.AlterField(
            model_name='userentity',
            name='status',
            field=models.BooleanField(choices=[(True, 'Follow'), (False, 'Unfollow')], default=True),
        ),
    ]
