# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 07:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='last_news',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
