# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-30 10:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss', '0001_initial'),
        ('entities', '0002_auto_20160830_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='last_news',
        ),
        migrations.AddField(
            model_name='entity',
            name='latest_news',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rss.News'),
        ),
    ]
