# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 10:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0002_auto_20160808_0712'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'Activated'), ('D', 'Deactivated')], default='A', max_length=1)),
                ('score', models.SmallIntegerField(default=0)),
                ('last_news', models.DateTimeField(blank=True, null=True)),
                ('news_count', models.IntegerField(default=0)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
