# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-05 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0003_auto_20160830_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='negative',
            field=models.ManyToManyField(related_name='_entity_negative_+', to='entities.Entity',
                                         verbose_name='Negative to Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='related',
            field=models.ManyToManyField(related_name='_entity_related_+', to='entities.Entity',
                                         verbose_name='Related to Entity'),
        ),
        migrations.AddField(
            model_name='entity',
            name='synonym',
            field=models.ManyToManyField(related_name='_entity_synonym_+', to='entities.Entity',
                                         verbose_name='Synonym to Entity'),
        ),
    ]
