# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_userentity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userentity',
            name='status',
            field=models.BooleanField(choices=[(True, 'Fallow'), (False, 'Unfallow')], default=True),
        ),
    ]
