# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-06 06:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0004_auto_20161105_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='for_search',
            field=models.CharField(default='Unknown', max_length=70),
            preserve_default=False,
        ),
    ]
