# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-14 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('entities', '0005_entity_for_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='positive',
            field=models.ManyToManyField(related_name='_entity_positive_+', to='entities.Entity',
                                         verbose_name='Positive to Entity'),
        ),
    ]
